### PR TITLE
[Runtime] add parameters for speed up unlock token

### PR DESCRIPTION
**Pull request by CaptainVincent**
Pus speeds up parameters on storage field.
1. Shorten time of the round (default round is 30 days)
2. Shorten cut down period (default period is 20 rounds)
> 2. will affect  the initial bucket size for keeping cut down ratio still 1/2 every periods.

Add one test with below parameters
1. shorten time of the round to original 1/4
2. shorten cut down period to original 1/2
and 
3. total time range is 600 days + 1 second

### CODE REVIEW

**Comment by dm4** [comment]
also update `genesis_testing.json`?

**Comment by dm4** [comment]
set `fraction_r = 100` and `fraction_p = 1` at testing genesis by default (by @hydai)

**Comment by CaptainVincent** [comment]
> set `fraction_r = 100` and `fraction_p = 1` at testing genesis by default (by @hydai)

done.

**Review by hydai — APPROVED** [review]
LGTM

**Review by dm4 — APPROVED** [review]
LGTM

**Pull request merged**
